# Generated by Django 4.2.11 on 2025-02-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationresult',
            name='created_at',
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='instructions',
            field=models.JSONField(null=True),
        ),
    ]
