# Generated by Django 4.2.11 on 2025-02-03 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_remove_classificationresult_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 2, 4)),
            preserve_default=False,
        ),
    ]
