# Generated by Django 4.2.11 on 2025-02-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_classificationresult_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationresult',
            name='instructions',
        ),
    ]
